config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # --- Django JET URLS ---
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/",
        include("jet.dashboard.urls", "jet-dashboard"),
    ),  # Django JET dashboard URLS
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.users.urls",
            namespace="users",
        ),
    ),
    path(
        "stores/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.stores.urls",
            namespace="stores",
        ),
    ),
    path(
        "warehouses/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.warehouses.urls",
            namespace="warehouses",
        ),
    ),
    path(
        "products/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.products.urls",
            namespace="products",
        ),
    ),
    path(
        "customers/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.customers.urls",
            namespace="customers",
        ),
    ),
    path(
        "employees/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.employees.urls",
            namespace="employees",
        ),
    ),
    path(
        "sales/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.sales.urls",
            namespace="sales",
        ),
    ),
    path(
        "address/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.addresses.urls",
            namespace="address",
        ),
    ),
    path(
        "logs/",
        include(
            "erp_villa_alemana_escolares_tecnologicos.apps.audits.urls",
            namespace="audits",
        ),
    ),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

erp_villa_alemana_escolares_tecnologicos/apps/addresses/urls.py
from django.urls import path

from .views import address_create_view
from .views import address_delete_view
from .views import address_detail_view
from .views import address_list_view
from .views import address_update_view

app_name = "address"
urlpatterns = [
    path("", address_list_view, name="address-list"),
    path("create/", address_create_view, name="address-create"),
    path("<int:pk>/", address_detail_view, name="address-detail"),
    path("<int:pk>/update/", address_update_view, name="address-update"),
    path("<int:pk>/delete/", address_delete_view, name="address-delete"),
]

erp_villa_alemana_escolares_tecnologicos/apps/audits/urls.py
from django.urls import path

from .views import audit_detail_view
from .views import audit_list_view

app_name = "audits"
urlpatterns = [
    path("", view=audit_list_view, name="list"),
    path("<int:pk>/", view=audit_detail_view, name="detail"),
]

erp_villa_alemana_escolares_tecnologicos/apps/customers/urls.py
from django.urls import path

from .views import customer_create_view
from .views import customer_delete_view
from .views import customer_detail_view
from .views import customer_list_view
from .views import customer_update_view

app_name = "customers"
urlpatterns = [
    path("customer/", view=customer_list_view, name="customer-list"),
    path("customer/create/", view=customer_create_view, name="customer-create"),
    path("customer/delete/<int:pk>", view=customer_delete_view, name="customer-delete"),
    path("customer/update/<int:pk>", view=customer_update_view, name="customer-update"),
    path(
        "customer/detail/<int:pk>/",
        view=customer_detail_view,
        name="customer-detail",
    ),
]

erp_villa_alemana_escolares_tecnologicos/apps/products/urls.py
from django.urls import path

from .views import product_category_create_view
from .views import product_category_delete_view
from .views import product_category_detail_view
from .views import product_category_list_view
from .views import product_category_update_view
from .views import product_create_view
from .views import product_delete_view
from .views import product_detail_view
from .views import product_list_view
from .views import product_update_view

app_name = "products"
urlpatterns = [
    path("product/", view=product_list_view, name="product-list"),
    path("product/create/", view=product_create_view, name="product-create"),
    path(
        "product/delete/<str:product_slug>",
        view=product_delete_view,
        name="product-delete",
    ),
    path(
        "product/update/<str:product_slug>",
        view=product_update_view,
        name="product-update",
    ),
    path(
        "product/detail/<str:product_slug>/",
        view=product_detail_view,
        name="product-detail",
    ),
    path(
        "category/",
        view=product_category_list_view,
        name="category-list",
    ),
    path(
        "category/create/",
        view=product_category_create_view,
        name="category-create",
    ),
    path(
        "category/delete/<str:category_slug>",
        view=product_category_delete_view,
        name="category-delete",
    ),
    path(
        "category/update/<str:category_slug>",
        view=product_category_update_view,
        name="category-update",
    ),
    path(
        "category/detail/<str:category_slug>/",
        view=product_category_detail_view,
        name="category-detail",
    ),
]

erp_villa_alemana_escolares_tecnologicos/apps/sales/urls.py
from django.urls import path

from .views import sale_create_view
from .views import sale_delete_view
from .views import sale_detail_view
from .views import sale_list_view
from .views import sale_update_view

app_name = "sales"
urlpatterns = [
    path("sale/", view=sale_list_view, name="sale-list"),
    path("sale/create/", view=sale_create_view, name="sale-create"),
    path("sale/delete/<int:pk>", view=sale_delete_view, name="sale-delete"),
    path("sale/update/<int:pk>", view=sale_update_view, name="sale-update"),
    path(
        "sale/detail/<int:pk>/",
        view=sale_detail_view,
        name="sale-detail",
    ),
]

erp_villa_alemana_escolares_tecnologicos/apps/stores/urls.py
from django.urls import path

from .views import store_create_view
from .views import store_delete_view
from .views import store_detail_view
from .views import store_employee_create_view
from .views import store_employee_delete_view
from .views import store_employee_detail_view
from .views import store_employee_list_view
from .views import store_list_view
from .views import store_update_view

app_name = "stores"
urlpatterns = [
    path("store/", view=store_list_view, name="store-list"),
    path("store/create/", view=store_create_view, name="store-create"),
    path("store/delete/<str:store_slug>", view=store_delete_view, name="store-delete"),
    path("store/update/<str:store_slug>", view=store_update_view, name="store-update"),
    path(
        "store/detail/<str:store_slug>/",
        view=store_detail_view,
        name="store-detail",
    ),
    path(
        "employee/",
        view=store_employee_list_view,
        name="employee-list",
    ),
    path(
        "employee/create/",
        view=store_employee_create_view,
        name="employee-create",
    ),
    path(
        "employee/delete/<int:pk>",
        view=store_employee_delete_view,
        name="employee-delete",
    ),
    path(
        "employee/detail/<int:pk>/",
        view=store_employee_detail_view,
        name="employee-detail",
    ),
]

erp_villa_alemana_escolares_tecnologicos/apps/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_group_detail_view
from .views import user_group_list_view
from .views import user_log_out_view
from .views import user_login_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("redirect/", view=user_redirect_view, name="redirect"),
    path("update/", view=user_update_view, name="update"),
    path("login/", view=user_login_view, name="login"),
    path("logout/", view=user_log_out_view, name="logout"),
    path("me/", view=user_detail_view, name="me"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("groups/", view=user_group_list_view, name="group-list"),
    path("groups/<str:slug>/", view=user_group_detail_view, name="group-detail"),
]

erp_villa_alemana_escolares_tecnologicos/apps/customers/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Customer


class CustomerCreateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "rut",
            "customer_type",
            "customer_class",
        )


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "rut",
            "customer_type",
            "customer_class",
        )


class CustomerDeleteForm(forms.ModelForm):
    confirmation = forms.BooleanField(label=_("confirmation"), required=False)

    class Meta:
        model = Customer
        fields = ()

erp_villa_alemana_escolares_tecnologicos/apps/addresses/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from erp_villa_alemana_escolares_tecnologicos.apps.utils.mixins import ModelContextMixin

from .forms import AddressCreateForm
from .forms import AddressUpdateForm
from .models import Address


class AddressDetailView(ModelContextMixin, PermissionRequiredMixin, DetailView):
    model = Address
    template_name = "address/address_detail.html"
    slug_field = "pk"
    slug_url_kwarg = "pk"
    context_object_name = "address"
    permission_required = "address.can_view_address"
    permission_denied_message = _("permission denied")


address_detail_view = AddressDetailView.as_view()


class AddressListView(ModelContextMixin, PermissionRequiredMixin, ListView):
    model = Address
    template_name = "address/address_list.html"
    context_object_name = "address"
    permission_required = "address.can_view_address"
    permission_denied_message = _("permission denied")


address_list_view = AddressListView.as_view()


class AddressCreateView(PermissionRequiredMixin, CreateView):
    model = Address
    template_name = "address/address_create.html"
    form_class = AddressCreateForm
    success_url = reverse_lazy("address:address-list")
    context_object_name = "address"
    permission_required = "address.can_add_address"
    permission_denied_message = _("permission denied")


address_create_view = AddressCreateView.as_view()


class AddressUpdateView(PermissionRequiredMixin, UpdateView):
    model = Address
    template_name = "address/address_update.html"
    form_class = AddressUpdateForm
    success_url = reverse_lazy("address:address-list")
    context_object_name = "address"
    permission_required = "address.can_edit_address"
    permission_denied_message = _("permission denied")


address_update_view = AddressUpdateView.as_view()


class AddressDeleteView(PermissionRequiredMixin, DeleteView):
    model = Address
    template_name = "address/address_delete.html"
    success_url = reverse_lazy("address:address-list")
    context_object_name = "address"
    permission_required = "address.can_edit_address"
    permission_denied_message = _("permission denied")


address_delete_view = AddressDeleteView.as_view()

erp_villa_alemana_escolares_tecnologicos/apps/audits/views.py
from auditlog.models import LogEntry
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import ListView

from erp_villa_alemana_escolares_tecnologicos.apps.utils.mixins import ModelContextMixin


class AuditListView(ModelContextMixin, PermissionRequiredMixin, ListView):
    model = LogEntry
    template_name = "audits/audit_list.html"
    context_object_name = "audits"
    paginate_by = 10
    paginator_class = Paginator
    permission_required = "auditlog.can_view_audit"
    permission_denied_message = _("permission denied")


audit_list_view = AuditListView.as_view()


class AuditDetailView(ModelContextMixin, PermissionRequiredMixin, DetailView):
    model = LogEntry
    template_name = "audits/audit_detail.html"
    context_object_name = "audit"
    slug_field = "pk"
    slug_url_kwarg = "pk"
    permission_required = "auditlog.can_view_audit"
    permission_denied_message = _("permission denied")


audit_detail_view = AuditDetailView.as_view()

erp_villa_alemana_escolares_tecnologicos/apps/customers/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from erp_villa_alemana_escolares_tecnologicos.apps.utils.mixins import ModelContextMixin

from .forms import CustomerCreateForm
from .forms import CustomerUpdateForm
from .models import Customer


class CustomerDetailView(ModelContextMixin, PermissionRequiredMixin, DetailView):
    model = Customer
    template_name = "customers/customer_detail.html"
    slug_field = "pk"
    slug_url_kwarg = "pk"
    context_object_name = "customer"
    permission_required = "customers.can_view_customer"
    permission_denied_message = _("permission denied")


customer_detail_view = CustomerDetailView.as_view()


class CustomerListView(ModelContextMixin, PermissionRequiredMixin, ListView):
    model = Customer
    template_name = "customers/customer_list.html"
    context_object_name = "customers"
    permission_required = "customers.can_view_customer"
    permission_denied_message = _("permission denied")


customer_list_view = CustomerListView.as_view()


class CustomerCreateView(PermissionRequiredMixin, CreateView):
    model = Customer
    template_name = "customers/customer_create.html"
    form_class = CustomerCreateForm
    success_url = reverse_lazy("customers:customer-list")
    context_object_name = "customer"
    permission_required = "customers.can_add_customer"


customer_create_view = CustomerCreateView.as_view()


class CustomerUpdateView(PermissionRequiredMixin, UpdateView):
    model = Customer
    template_name = "customers/customer_update.html"
    form_class = CustomerUpdateForm
    success_url = reverse_lazy("customers:customer-list")
    context_object_name = "customer"
    permission_required = "customers.can_change_customer"
    permission_denied_message = _("permission denied")


customer_update_view = CustomerUpdateView.as_view()


class CustomerDeleteView(PermissionRequiredMixin, DeleteView):
    model = Customer
    template_name = "customers/customer_delete.html"
    success_url = reverse_lazy("customers:customer-list")
    context_object_name = "customer"
    permission_required = "customers.can_delete_customer"
    permission_denied_message = _("permission denied")


customer_delete_view = CustomerDeleteView.as_view()

erp_villa_alemana_escolares_tecnologicos/templates/components/auto_table.html
{% load humanize %}
{% load model_utils %}

<table class="table {% if table_class %}{{ table_class }}{% endif %}">
    <thead>
        <tr>
            {% for field in fields %}<th>{{ field.verbose_name|title }}</th>{% endfor %}
            {% if detail_url_name or edit_url_name %}<th>Actions</th>{% endif %}
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
            <tr>
                {% for field in fields %}
                    <td>
                        {% with value=object|get_attribute:field.name %}
                            {% if field.is_relation %}
                                {{ value|default_if_none:"-" }}
                            {% elif field.get_internal_type == 'DecimalField' %}
                                {{ value|floatformat:2 }}
                            {% elif field.get_internal_type == 'DateField' %}
                                {{ value|date:"Y-m-d" }}
                            {% elif field.get_internal_type == 'DateTimeField' %}
                                {{ value|date:"Y-m-d H:i" }}
                            {% elif field.get_internal_type == 'BooleanField' %}
                                {{ value|yesno:"Yes,No" }}
                            {% else %}
                                {{ value|default:"-"|truncatechars:50 }}
                            {% endif %}
                        {% endwith %}
                    </td>
                {% endfor %}
                {% if detail_url_name or edit_url_name %}
                    <td>
                        {% if detail_url_name %}
                            <button>
                                <a class="contrast"
                                   href="{% if use_slug %}{% url detail_url_name object.slug %}{% else %}{% url detail_url_name object.pk %}{% endif %}">
                                    View
                                </a>
                            </button>
                        {% endif %}
                        {% if edit_url_name %}
                            <button>
                                <a class="contrast"
                                   href="{% if use_slug %}{% url edit_url_name object.slug %}{% else %}{% url edit_url_name object.pk %}{% endif %}">
                                    Edit
                                </a>
                            </button>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% empty %}
            <tr>
                <td colspan="{{ fields|length|add:1 }}" class="text-center">No items found</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

erp_villa_alemana_escolares_tecnologicos/templates/components/footer.html
<footer>
    <div class="container">
        <p>
            <small>
                &copy; 2025 Diego Rivera
                <a href="{% url 'warehouses:warehouse-list' %}" class="active">Bodegas</a>
                <a href="{% url 'stores:store-list' %}" class="active">Tiendas</a>
                <a href="{% url 'employees:employee-list' %}" class="active">Empleados</a>
                <a href="{% url 'products:product-list' %}" class="active">Productos</a>
                <a href="{% url 'customers:customer-list' %}" class="active">Clientes</a>
                <a href="{% url 'sales:sale-list' %}" class="active">Ventas</a>
                <a href="{% url 'address:address-list' %}" class="active">Direcciones</a>
                <a href="{% url 'audits:list' %}" class="active">Logs</a>
            </small>
        </p>
    </div>
</footer>

erp_villa_alemana_escolares_tecnologicos/templates/components/header.html
{% load static %}

<header class="container">
    <nav>
        <!-- Logo y marca -->
        <div>
            <a href="{% url 'home' %}" class="logo contrast">
                <img src="{% static 'images/logo.jpeg' %}"
                     height="50"
                     width="50"
                     alt="imagen logo" />
                <h1>ERP Villa alemana</h1>
                <small>Gestion Empresarial</small>
            </a>
        </div>
        <!-- Navegación principal -->
        <ul class="nav-list">
            {% if perms.warehouses.can_view_warehouse %}
                <li>
                    <a href="{% url 'warehouses:warehouse-list' %}" class="active">Bodegas</a>
                </li>
            {% endif %}
            {% if perms.stores.can_view_store %}
                <li>
                    <a href="{% url 'stores:store-list' %}" class="active">Tiendas</a>
                </li>
            {% endif %}
            {% if perms.employees.can_view_employee %}
                <li>
                    <a href="{% url 'employees:employee-list' %}" class="active">Empleados</a>
                </li>
            {% endif %}
            {% if perms.products.can_view_product %}
                <li>
                    <a href="{% url 'products:product-list' %}" class="active">Productos</a>
                </li>
            {% endif %}
            {% if perms.customers.can_view_customer %}
                <li>
                    <a href="{% url 'customers:customer-list' %}" class="active">Clientes</a>
                </li>
            {% endif %}
            {% if perms.sales.can_view_sale %}
                <li>
                    <a href="{% url 'sales:sale-list' %}" class="active">Ventas</a>
                </li>
            {% endif %}
            {% if perms.addresses.can_view_address %}
                <li>
                    <a href="{% url 'address:address-list' %}" class="active">Direcciones</a>
                </li>
            {% endif %}
            {% if perms.auditlog.view_logentry %}
                <li>
                    <a href="{% url 'audits:list' %}" class="active">Logs</a>
                </li>
            {% endif %}
            {% if user.is_staff %}
                <li>
                    <a href="{% url 'admin:index' %}" class="active">Admin</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</header>

erp_villa_alemana_escolares_tecnologicos/templates/components/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}